### ISSUE TITLE
Export in GDWeave/mods folder

### ISSUE THREAD

**Issue by keetsta** [NotNite/manifestation#4]
Export happens in mod directory and not in the GDWeave directory itself, which is quite annoying. Cs exports in mod directory tho, so yeah here is the feature request / feature approval cuz i could just PR this if you don't mind

**Comment by NotNite** [comment]
I could add an argument to copy to the game directory, maybe?

**Comment by keetsta** [comment]
> I could add an argument to copy to the game directory, maybe?

It would be nice!

**Comment by Awesomerly** [comment]
I made a script that does that but it would be nice to have it in the base program

**Comment by Awesomerly** [comment]
This should be in the latest version of manifestation!
